name: currency-db-check

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * */12 * *'

jobs:
  check-if-currency-database-updated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: checkout repo

      - name: Check if currencies data was updated
        continue-on-error: false
        run: |
          chmod +x ./scripts/compare_currency_data.sh 
          ./scripts/compare_currency_data.sh
        shell: bash

      - name: Commit and push changes
        run: |
          git config --global user.name "GLEF1X"
          git config --global user.email "glebgar567@gmail.com"
          git add -A
          git commit -m "Update currency db"
          git push origin master