name: 'Build && publish package to pypi'

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ 'Autoupdate currency data' ]
    types:
      - completed

jobs:
  build:
    name: Build

    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -U pip virtualenv poetry bump2version
          poetry config virtualenvs.create false

      - name: Bump version
        run: |
          set -x
          git config --global user.name "GLEF1X"
          git config --global user.email "glebgar567@gmail.com"
          git pull -s recursive -X theirs
          bump2version patch

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true

      - name: Build
        run: |
          poetry build -n -vvv

      - name: Try install wheel
        run: |
          mkdir -p try_install
          cd try_install
          virtualenv venv
          venv/bin/pip install ../dist/python_iso4217-*.whl

      - name: Publish artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist/*

  publish:
    name: Publish
    needs: build
    if: "success()"
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
